

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd example
    yarn
  displayName: 'Install example packages'

- script: yarn
  displayName: 'Install packages'

- script: |
    yarn publish --non-interactive
  displayName: 'publish release to npm'
